server:
    port: 8090
spring:
    datasource:
        url: jdbc:h2:mem:testdb
        driverClassName: org.h2.Driver
        username: sa
        password: ''
    h2:
        console:
            path: /h2
            enabled: true
    jpa:
        hibernate:
            ddl-auto: update
        open-in-view: true
        show-sql: true
